### ISSUE TITLE
Python virtualenv DAG failed with "No such file or directory: 'virtualenv': 'virtualenv'"

### ISSUE THREAD

**Issue by sturivny** [CSCfi/airflow-openshift#8]
__Precondition:__
AirflowTemplate.yml deployed on OpenShift cluster
```
openshift v3.11.154
kubernetes v1.11.0+d4cacc0
```
__Steps:__
Run a DAG from the example: https://github.com/apache/airflow/blob/master/airflow/example_dags/example_python_operator.py

and getting this error:
```
--------------------------------------------------------------------------------
[2021-02-22 16:33:39,610] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-02-22 16:33:39,610] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-02-22 16:33:39,624] {taskinstance.py:901} INFO - Executing <Task(PythonVirtualenvOperator): virtualenv_python> on 2021-02-22T16:33:36.759403+00:00
[2021-02-22 16:33:39,627] {standard_task_runner.py:54} INFO - Started process 267 to run task
[2021-02-22 16:33:39,645] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'example_python_virtualenv', 'virtualenv_python', '2021-02-22T16:33:36.759403+00:00', '--job_id', '27', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/virtualenv.py', '--cfg_path', '/tmp/tmpetrfe31m']
[2021-02-22 16:33:39,646] {standard_task_runner.py:78} INFO - Job 27: Subtask virtualenv_python
[2021-02-22 16:33:39,689] {logging_mixin.py:112} INFO - Running <TaskInstance: example_python_virtualenv.virtualenv_python 2021-02-22T16:33:36.759403+00:00 [running]> on host worker-3-2hhwl
[2021-02-22 16:33:39,713] {python_operator.py:316} INFO - Executing cmd
['virtualenv', '/tmp/venvxhuyqyz2']
[2021-02-22 16:33:39,720] {taskinstance.py:1150} ERROR - [Errno 2] No such file or directory: 'virtualenv': 'virtualenv'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 292, in execute_callable
    self._execute_in_subprocess(self._generate_virtualenv_cmd(tmp_dir))
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 319, in _execute_in_subprocess
    close_fds=True)
  File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv': 'virtualenv'
[2021-02-22 16:33:39,722] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=example_python_virtualenv, task_id=virtualenv_python, execution_date=20210222T163336, start_date=20210222T163339, end_date=20210222T163339
[2021-02-22 16:33:44,586] {local_task_job.py:102} INFO - Task exited with return code 1
```

Would be great if you could point where to look at.
Thanks

**Comment by MWargelin** [comment]
Hello! Sorry for ignoring you for so long. This project has been on hiatus and this issue went unnoticed. We now made a major revision to the template and switched to use the official Airflow image as well as Airflow v2 instead of v1, and as a side product the PythonVirtualenvOperator seems to have started working :) Please let us know if the issue remains!

**Comment by sturivny** [comment]
Thanks
